### ISSUE TITLE
Thousands of looping "python object' errors

### ISSUE THREAD

**Issue by vk2him** [xannor/ha_reolink_rest#11]
I'm seeing a continual log of errors that keep looping and never end - the following error is from the logs and keeps growing.

Logger: custom_components.reolink_rest
Source: util/logging.py:62
Integration: Reolink Device ([documentation](https://github.com/xannor/ha_reolink_rest), [issues](https://github.com/xannor/ha_reolink_rest/issues))
First occurred: 9:06:13 AM (2 occurrences)
Last logged: 9:08:00 AM

Unexpected error fetching reolink_rest-Driveway data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/config/custom_components/reolink_rest/entity.py", line 286, in async_update
    self.abilities = await self.client.get_ability(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/system/__init__.py", line 159, in get_ability
    result = await anext(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/utils.py", line 166, in amap
    async for item in __async_iterable:
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/utils.py", line 153, in afilter
    async for item in __iterable:
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands.py", line 296, in async_trap_errors
    _raise_response_error(code, error["detail"])
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands.py", line 243, in _raise_response_error
    raise ReolinkResponseError(code=code, details=details)
async_reolink.api.errors.ReolinkResponseError: please login first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/reolink_rest/entity.py", line 286, in async_update
    self.abilities = await self.client.get_ability(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/system/__init__.py", line 159, in get_ability
    result = await anext(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/utils.py", line 166, in amap
    async for item in __async_iterable:
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/utils.py", line 153, in afilter
    async for item in __iterable:
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands.py", line 296, in async_trap_errors
    _raise_response_error(code, error["detail"])
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands.py", line 243, in _raise_response_error
    raise ReolinkResponseError(code=code, details=details)
async_reolink.api.errors.ReolinkResponseError: please login first

This is my Camera details - you can see there's no preview for the camera against the entities:

![Image 001](https://user-images.githubusercontent.com/22878629/185259702-56a95f91-a0ff-41bc-a1e8-fde4809d7181.jpg)

**Comment by xannor** [comment]
This is something I have noticed as well when the authentication screws up. At some point the camera decides that the token is no good, and there is a hole in the code that gets stuck in the loop. Sometimes restarting home assistant will fix this, sometimes restart both home assistant and the camera is needed. I am working on a major code overhaul that will address this, and a few other issues.

**Comment by vk2him** [comment]
Thanks - the log file gets big quickly when this happens. 

As further clues for you - On my system at least, I can "force" it to break after a few hours if I create a card that displays the snapshot (which is updated each second) unless it detects motion when it displays the live feed as follows. I assumed it was some sort of memory leak which caused it to fail but that's a guess.

```
type: custom:state-switch
entity: template
template: >-
  {% if states('binary_sensor.driveway_motion') == 'off' %} idle {% else %}
  recording {% endif %}
states:
  idle:
    type: picture-entity
    entity: camera.driveway_snapshot_extra
    camera_view: live
    show_name: false
    show_state: false
  recording:
    type: picture-entity
    entity: camera.driveway_rtmp_extra
    camera_view: live
    show_name: false
    show_state: false
```
